name: Flow B

on:
  workflow_dispatch:
    inputs:
      variable_b:
        description: 'example var'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ci
        run: |
          echo ${{ github.event.inputs.variable_b }}