name: Flow B

on:
  workflow_call:
    inputs:
      variable_b:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print B
        run: |
          echo ${{ inputs.variable_b }}
          echo "${{ inputs.variable_b }}"
          env