name: Flow A

on:
  workflow_call:
    inputs:
      variable_a:
        description: 'example var'
        required: true
        type: string

jobs:
  test:
    name: test
    uses: 6rendon/cicd-testing/.github/workflows/flow_b.yml@main
    with:
      variable_b: ${{ github.event.inputs.variable_a }}