name: testing

on:
  push:


permissions:
  id-token: write
  contents: read

jobs:
  init:
    name: Init
    uses: 6rendon/cicd-testing/.github/workflows/phx-dev.yml@main
    with:
      build-args: |
        test=BRENDON
        foo=${{ secrets.SECRET_TOKEN }}
    secrets:
      secret-token: ${{ secrets.SECRET_TOKEN }}