name: Flow A

on:
  workflow_call:
    inputs:
      build-args:
        required: true
        type: string
    secrets:
      secret-token:
        required: true

jobs:
  build:
    name: test
    uses: 6rendon/cicd-testing/.github/workflows/flow_b.yml@main
    with:
      build-args: ${{ inputs.build-args }}
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "${{ secrets.secret-token }}"