name: Flow A

on:
  workflow_call:
    inputs:
      build-args:
        required: true
        type: string

jobs:
  build:
    name: test
    uses: 6rendon/cicd-testing/.github/workflows/flow_b.yml@main
    with:
      build-args: ${{ inputs.build-args }}