name: Flow A

on:
  workflow_call:
    inputs:
      # build-args:
      #   required: true
      #   type: string
    secrets:
      secret-token:
        required: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "NPM_TOKEN=${NPM_TOKEN_ENV}" >> $GITHUB_ENV
        env: 
          NPM_TOKEN_ENV: ${{ secrets.secret-token }}
  build:
    needs: [test]
    name: build
    uses: 6rendon/cicd-testing/.github/workflows/flow_b.yml@main
    with:
      build-args: |
        foo=BAR
        test=$NPM_TOKEN